### ISSUE TITLE
管理员邮箱验证不了，没法收到信息

### ISSUE THREAD

**Issue by yeyinghai** [a76yyyy/qd#3]
管理员邮箱验证不了，没法收到信息
大佬，咋回事，

**Comment by a76yyyy** [comment]
请检查管理员邮箱配置是否正确

**Comment by yeyinghai** [comment]
大佬，邮件信息对着呢，没有问题啊。这个老是不能验证，能帮忙具体看看咋回事或者怎么解决吗？谢谢您




***@***.***
 
发件人： a76yyyyy
发送时间： 2021-09-03 22:55
收件人： a76yyyy/qiandao
抄送： yeyinghai; Author
主题： Re: [a76yyyy/qiandao] 管理员邮箱验证不了，没法收到信息 (#3)
请检查管理员邮箱配置是否正确
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by a76yyyy** [comment]
发一下邮箱配置信息吧，记得脱敏

**Comment by yeyinghai** [comment]
谢谢大佬













在 2021-09-05 17:04:16，"a76yyyyy" ***@***.***> 写道：

发一下邮箱配置信息吧，记得脱敏

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by a76yyyy** [comment]
我好像没有收到你的邮箱配置信息，请确认你已发送

**Comment by yeyinghai** [comment]
![image](https://user-images.githubusercontent.com/15318670/132636638-38281e35-3fba-4406-ae94-0bbe39612980.png)
谢谢大佬

**Comment by a76yyyy** [comment]
已经解决了么？

**Comment by yeyinghai** [comment]
没有，您看下配置。还是不能验证邮箱

**Comment by a76yyyy** [comment]
怀疑是你的邮箱没有开启smtp，或者你的邮箱密码错误，请检查是否设置了专用的smtp密码

**Comment by yeyinghai** [comment]
邮箱开启有smtp，密码我用的登录密码和授权码都试过了

**Comment by yeyinghai** [comment]
新注册的号，提成管理员也不会收到信息
能不能直接改数据库把账号的邮箱弄成验证

**Comment by a76yyyy** [comment]
可以的，直接进入数据库里把user表里对应账户的email_verified值改为1

**Comment by yeyinghai** [comment]
直接打开config里面的db文件是吧，vi不能编辑啊，用哪个修改，大佬

**Comment by yeyinghai** [comment]
大佬，现在新用户注册邮箱能收到从管理员邮箱发送的验证信息，但验证信息链接是您的，这个咋回事
![image](https://user-images.githubusercontent.com/15318670/133012634-38d1d1bf-07e1-4501-88f8-04fb4152b8e7.png)

**Comment by a76yyyy** [comment]
> 直接打开config里面的db文件是吧，vi不能编辑啊，用哪个修改，大佬

请学习sqlite3数据库操作方法，或者通过navicat等软件实现数据库的可视化操作

**Comment by a76yyyy** [comment]
> 大佬，现在新用户注册邮箱能收到从管理员邮箱发送的验证信息，但验证信息链接是您的，这个咋回事
> ![image](https://user-images.githubusercontent.com/15318670/133012634-38d1d1bf-07e1-4501-88f8-04fb4152b8e7.png)

- 如果是通过源码建立框架的话，请在框架根目录下新建local_config.py添加并修改以下内容:

```
# 框架运行ip(0.0.0.0表示监听所有IP地址)、端口port、是否通过https访问
bind = str(os.getenv('BIND', '0.0.0.0'))
port = int(os.getenv('PORT', 8923))
https = bool(os.getenv('ENABLE_HTTPS', False))

# 发送邮件内显示的域名，如果是通过IP+端口Port方式请正确输入`IP:Port`
domain = os.getenv('DOMAIN', 'qiandao.today')

# 邮件发送相关设置
mail_smtp = os.getenv('MAIL_SMTP',"")
mail_port = int(os.getenv('MAIL_PORT', 465))
mail_ssl = True
mail_user = os.getenv('MAIL_USER', '')
mail_password = os.getenv('MAIL_PASSWORD', '')
```

- 如果是通过容器构建，请确认在`docker run`的时候正确设置好`--env DOMAIN=域名`这一环境变量

**Comment by yeyinghai** [comment]
谢谢大佬，弄好了，我直接修改config.py里面的域名。非常感谢您的耐心回答

**Comment by a76yyyy** [comment]
> 谢谢大佬，弄好了，我直接修改config.py里面的域名。非常感谢您的耐心回答

还是建议请先在框架根目录下新建local_config.py, 在linux环境下可执行以下命令
`cp config.py local_config.py`
修改local_config.py文件的内容不受通过git更新源码的影响

**Comment by yeyinghai** [comment]
好的，谢谢大佬的指点



在 2021-09-13 12:10:16，"a76yyyyy" ***@***.***> 写道：

谢谢大佬，弄好了，我直接修改config.py里面的域名。非常感谢您的耐心回答

还是建议请先在框架根目录下新建local_config.py, 在linux环境下可执行以下命令
cp config.py local_config.py
修改local_config.py文件的内容不受通过git更新源码的影响

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
