### ISSUE TITLE
[Bug]数据备份后恢复数据丢失分组信息

### ISSUE THREAD

**Issue by SeanSuny** [a76yyyy/qd#4]
数据备份中有分组信息，恢复后只有 **备份还原** 这一个分组
备份文件中签到模块和模板模块的分组信息如图：
![飞书20210906-104242](https://user-images.githubusercontent.com/20199755/132153201-accf8fd4-e07e-41e3-9b6b-77ad7a0637a9.png)
![202196-104248](https://user-images.githubusercontent.com/20199755/132153253-664396e0-086f-47fe-82d0-3a5eb694dc58.png)
恢复后签到模块和模板模块的分组信息如图：
![202196-104259](https://user-images.githubusercontent.com/20199755/132153279-e8902585-a550-48b4-9472-a1e057e40d24.png)
![202196-104253](https://user-images.githubusercontent.com/20199755/132153286-2ec4aa40-1a64-4d5c-b838-894f233fb937.png)

**Comment by a76yyyy** [comment]
为了避免冲突，目前先保持该逻辑
